import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import LanguageDropdown from "@/components/LanguageDropdown";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: "en" | "ka" };
}>) {
  const messages = await getMessages();

  const locale = params.locale;

  const fontClass = locale === "en" ? geistSans.variable : geistMono.variable;

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang='en'>
        <body className={`${fontClass} antialiased`}>
          <LanguageDropdown />
          {children}
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
